name: 'Lint Action'
description: 'Perform linting for project'
inputs:
  run_linting:
    description: 'Run Linting and also upload to artifactory'
    required: true
    default: 'false'
  upload_to_artifactory:
    description: 'Flag to control whether to upload reports to Artifactory'
    required: false
    default: 'false'

permissions:
  contents: read
#Adding Permission as Read for all of the available permissions

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint black isort
        pip install flake8-html pylint-report
      shell: bash

    - name: Run Black Formatting Check
      continue-on-error: true
      run: |
        mkdir -p reports/black
        black --check . > reports/black/formatting-check.txt
      shell: bash

    - name: Run Flake8 Linting
      continue-on-error: true
      run: |
        mkdir -p reports/flake8
        flake8 --format=html --htmldir=reports/flake8 .
      shell: bash

    - name: Run Pylint
      continue-on-error: true
      run: |
        mkdir -p reports/pylint
        pylint **/*.py > reports/pylint/pylint-report.txt
      shell: bash

    - name: Run Isort Import Sorting Check
      continue-on-error: true
      run: |
        mkdir -p reports/isort
        isort --check-only . > reports/isort/import-check.txt
      shell: bash

    - name: Upload Linting Reports
      if: ${{ inputs.upload_to_artifactory == 'true' || inputs.run_linting == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: linting-reports
        path: reports/