name: 'Black Formatting Action'
description: 'Perform linting for Python project'
inputs:
  checkout_directory:
    description: "Checkout directory to where ingredient repo content is to be copied."
    default: "src"
  ref:
    description: "Branch to checkout. By default, it will take the short ref name of the branch or tag that triggered the workflow run."
    required: false
  token:
    description: "GitHub token to fetch source"
    required: false
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10.11'
  upload_to_artifactory:
    description: 'Flag to control whether to upload to Artifactory'
    required: false
    default: 'false'

permissions: read-all
# Adding Permission as Read for all of the available permissions

runs:
  using: 'composite'
  steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4
    #   with:
    #     path: ${{ inputs.checkout_directory }}
    #     ref: ${{ inputs.ref || github.ref }}
    #     token: ${{ inputs.token || github.token }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install black
      shell: pwsh

    - name: Run Black and capture output
      run: |
        black --check --diff --quiet . > black_output.txt || true
      shell: pwsh

    - name: Show Black output
      run: cat black_output.txt
      shell: pwsh

    - name: Upload Black output as artifact
      # if: ${{ inputs.upload_to_artifactory == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: black-output
        path: black_output.txt