name: Setup Python and Package
description: This action sets up Python and installs necessary packages.
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10.11'

permissions: read-all # Adding Permission as Read for all of the available permissions

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'

    - name: Verify Python in PATH and Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        python -m pip install pyinstaller-versionfile
      shell: pwsh

    - name: Verify PyInstaller Installation
      run: |
        python --version
        pyinstaller --version
      shell: pwsh