name: Setup Python and Package
description: This action sets up Python and installs necessary packages.
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10.11'

runs:
  using: "composite"
  steps:
    - name: Download and Install Python
      run: |
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/${{ inputs.python-version }}/python-${{ inputs.python-version }}-amd64.exe" -OutFile "python-installer.exe"
        Start-Process -FilePath "python-installer.exe" -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1 TargetDir=C:\Python310" -Wait
      shell: pwsh

    - name: Verify Python Installation
      run: |
        dir C:\Python310
        C:\Python310\python.exe --version
      shell: pwsh

    - name: Install dependencies
      run: |
        C:\Python310\python.exe -m pip install --upgrade pip
        C:\Python310\python.exe -m pip install pyinstaller
        C:\Python310\python.exe -m pip install pyinstaller-versionfile
      shell: pwsh

    - name: Set up environment variables for PyInstaller
      run: |
        $env:PYTHONPATH = "C:\Python310"
        $env:PATH += ";C:\Python310;C:\Python310\Scripts"
        [Environment]::SetEnvironmentVariable("PYTHONPATH", $env:PYTHONPATH, [EnvironmentVariableTarget]::Process)
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH, [EnvironmentVariableTarget]::Process)
      shell: pwsh