name: Setup Python and Package
description: This action sets up Python and installs necessary packages.
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10.11'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Copy Python to C:\Python310
      run: |
        $pythonPath = (Get-Command python).Path
        $pythonDir = Split-Path -Parent $pythonPath
        if (-Not (Test-Path -Path "C:\Python310")) {
          New-Item -ItemType Directory -Path "C:\Python310"
        }
        Copy-Item -Path "$pythonDir\*" -Destination "C:\Python310" -Recurse -Force
      shell: pwsh

    - name: Verify Python Installation
      run: |
        if (Test-Path -Path "C:\Python310\python.exe") {
          Write-Host "Python installed successfully."
          C:\Python310\python.exe --version
        } else {
          Write-Error "Python installation failed."
          exit 1
        }
      shell: pwsh

    - name: Set up environment variables for Python
      run: |
        $env:PYTHONPATH = "C:\Python310"
        $env:PATH = "C:\Python310;C:\Python310\Scripts;" + $env:PATH
        [Environment]::SetEnvironmentVariable("PYTHONPATH", $env:PYTHONPATH, [EnvironmentVariableTarget]::Process)
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH, [EnvironmentVariableTarget]::Process)
      shell: pwsh

    - name: Verify Python in PATH
      run: |
        python --version
      shell: pwsh

    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        python --version
        python -m pip install pyinstaller
        python --version
        python -m pip install pyinstaller-versionfile
      shell: pwsh