name: Setup Python and Package
description: This action sets up Python and installs necessary packages.
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pyinstaller-versionfile
      shell: pwsh
    
    - name: Set up environment variables for PyInstaller
      run: |
        $env:PYTHONPATH = "${{ runner.tool_cache }}\Python\${{ inputs.python-version }}\x64"
        $env:PATH += ";${{ runner.tool_cache }}\Python\${{ inputs.python-version }}\x64\Scripts"
        [Environment]::SetEnvironmentVariable("PYTHONPATH", $env:PYTHONPATH, [EnvironmentVariableTarget]::Process)
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH, [EnvironmentVariableTarget]::Process)
      shell: pwsh