name: Build The Project
description: This action builds the project and uploads it to the Artifactory.
inputs:
  upload_to_artifactory:
    description: 'Flag to control whether to upload to Artifactory'
    required: false
    default: 'false'

permissions: read-all
# Adding read permissions for all available permissions

runs:
  using: "composite"
  steps:
    - name: Run Build
      run: |
        cd build
        .\Build.bat
      shell: pwsh

    - name: Prepare files for upload
      run: |
        mkdir -p upload
        cp dist/* upload/
        cp -r AIDevKit upload/
        cp CHANGELOG.md upload/
        cp License.txt upload/
        cp Installation_Guide.md upload/README.md
      shell: pwsh
    
    - name: Upload binary as artifact
      if: ${{ inputs.upload_to_artifactory == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ArtifactAIPC
        path: upload/
