name: 'Semgrep Actions Scan'
description: 'Perform security scanning using semgrep'
inputs:
  checkout_directory:
    description: "checkout directory to where ingredient repo content is to be copied."
    default: "src"
  ref:
    description: "branch to checkout, by default It will take the short ref name of the branch or tag that triggered the workflow run."
    required: false
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.10.11'
  token:
    description: "Github token to fetch source"
    required: false
  # Semgrep specific inputs
  semgrep_version:
    description: 'semgrep version to use'
    required: false
    default: '1.100.0'
  report_name:
    description: 'Name of the report file'
    required: false
    default: 'semgrep-results'

runs:
  using: 'composite'
  steps:
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: Install Semgrep
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install semgrep==${{ inputs.semgrep_version }}
    
    - name: Perform Semgrep Analysis
      # @NOTE: This is the actual semgrep command to scan your code.
      # Modify the --config option to 'r/all' to scan using all rules,
      # or use multiple flags to specify particular rules, such as
      # --config r/all --config custom/rules
      run: |
        # Basic scan with default
        semgrep --json --metrics=off --config=r/all --output ${{ inputs.report_name }}.json
      shell: bash
    
    - name: Upload Semgrep Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.report_name }}
        path: ${{ inputs.report_name }}.json