name: Coverity Scan with Community Credentials
description: "This action installs a specific version of Coverity."

inputs:
  checkout_directory:
    description: "checkout directory to where ingredient repo content is to be copied."
    default: "src"
  ref:
    description: "branch to checkout, by default It will take the short ref name of the branch or tag that triggered the workflow run."
    required: false
  # Coverity Parameters )
  project:
    description: Project name in Coverity Scan.
    default: ${{ github.repository }}
    required: false
  token:
    description: Secret project token for accessing Coverity Scan.
    required: true
  email:
    description: Where Coverity Scan should send notifications.
    required: true
  build_language:
    description: Which Coverity Scan language pack to download.
    default: cxx
    required: false
  build_platform:
    description: Which Coverity Scan platform pack to download.
    default: linux64
    required: false
  command:
    description: Command to pass to cov-build.
    default: make
    required: false
  working-directory:
    description: Working directory to set for all steps.
    default: ${{ github.workspace }}
    required: false
  version:
    description: (Informational) The source version being built.
    default: ${{ github.sha }}
    required: false
  description:
    description: (Informational) A description for this particular build.
    default: coverity-scan-action ${{ github.repository }} / ${{ github.ref }}
    required: false
  report_name:
    description: 'Name of the report file'
    required: false
    default: 'coverity-results'

runs: 
  using: "composite"
  steps:
    # Need to encode the project name when using in URLs and HTTP forms.  Valid
    # GitHub project names only have / that need encoding and
    # Coverity projects with spaces in their names need encoding so do
    # an ad-hoc conversion here.  Wait to see if anyone needs something else.
    - name: URL encode project name
      id: project
      run: echo "project=${{ inputs.project }}" | sed -e 's:/:%2F:g' -e 's/ /%20/g' >> $GITHUB_OUTPUT
      shell: bash

    # The Coverity site says the tool is usually updated twice yearly, so the
    # md5 of download can be used to determine whether there's been an update.
    - name: Lookup Coverity Build Tool hash
      id: coverity-cache-lookup
      run: |
        hash=$(curl https://scan.coverity.com/download/${{ inputs.build_language }}/${{ inputs.build_platform }} \
                --data "token=${TOKEN}&project=${{ steps.project.outputs.project }}&md5=1"); \
        echo "hash=${hash}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}

    # Try to cache the tool to avoid downloading 1GB+ archive on every run.
    # Cache miss will add ~30s to create, but cache hit will save minutes.
    - name: Cache Coverity Build Tool
      id: cov-build-cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-directory }}/cov-analysis
        key: cov-build-${{ inputs.build_language }}-${{ inputs.build_platform }}-${{ steps.coverity-cache-lookup.outputs.hash }}

    - name: Download Coverity Build Tool (${{ inputs.build_language }} / ${{ inputs.build_platform }})
      if: steps.cov-build-cache.outputs.cache-hit != 'true'
      run: |
        curl https://scan.coverity.com/download/${{ inputs.build_language }}/${{ inputs.build_platform }} \
          --no-progress-meter \
          --output cov-analysis.tar.gz \
          --data "token=${TOKEN}&project=${{ steps.project.outputs.project }}"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        TOKEN: ${{ inputs.token }}

    - if: steps.cov-build-cache.outputs.cache-hit != 'true'
      run: mkdir cov-analysis
      shell: bash
      working-directory: ${{ inputs.working-directory }}
  
    - if: steps.cov-build-cache.outputs.cache-hit != 'true'
      run: tar -xzf cov-analysis.tar.gz --strip 1 -C cov-analysis
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Build with cov-build
      run: |
        export PATH="${PWD}/cov-analysis/bin:${PATH}"
        cov-build --dir cov-int ${{ inputs.command }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    
    - name: Archive results
      run: tar -czvf ${{ inputs.report_name }}.tgz cov-int
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    
    - name: Upload Coverity Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.report_name }}
        path: ${{ inputs.report_name }}.tgz
    
    # - name: Submit results to Coverity Scan
    #   run: |
    #     curl \
    #       --form token="${TOKEN}" \
    #       --form email="${{ inputs.email }}" \
    #       --form file=@${{ inputs.report_name }}.tgz \
    #       --form version="${{ inputs.version }}" \
    #       --form description="${{ inputs.description }}" \
    #       "https://scan.coverity.com/builds?project=${{ steps.project.outputs.project }}"
    #   shell: bash
    #   working-directory: ${{ inputs.working-directory }}
    #   env:
    #     TOKEN: ${{ inputs.token }}

    # - name: Analysis with cov-analyze
    #   run: |
    #     cov-analyze --dir cov-int --all
    #   shell: bash
    #   working-directory: ${{ inputs.working-directory }}
    
    # - name: Generate report with cov-format-errors
    #   run: |
    #     cov-format-errors --dir cov-int --json-output-v2 ${{ inputs.report_name }}.json
    #   shell: bash
    #   working-directory: ${{ inputs.working-directory }}
    
    # - name: Upload Coverity Scan Results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ inputs.report_name }}
    #     path: ${{ inputs.report_name }}.json